#!/usr/bin/env sh
#
# i3 hotkeys
#

super + space 
    albert show

# wm independent hotkeys
#

super + shift + s
    screenshot

control + super + s
    bwmenu 

control + alt + t
    kitty

XF86AudioMute
    pactl set-sink-mute @DEFAULT_SINK@ toggle

{XF86AudioRaiseVolume, XF86AudioLowerVolume}
    pactl set-sink-mute @DEFAULT_SINK@ false; pactl set-sink-volume @DEFAULT_SINK@ {+,-}5%

{XF86MonBrightnessUp, XF86MonBrightnessDown}
    xbacklight -{inc,dec} 5%
