#!/usr/bin/env sh
#
# bspwm hotkeys
#

#
# wm independent hotkeys
#

control + super + s
    ~/.nix-profile/bin/fish -c ~/.bw-scripts/slab.sh

control + super + 2
    ~/.nix-profile/bin/fish -c ~/.bw-scripts/2fa.sh

control + super + u
    ~/.nix-profile/bin/fish -c ~/.bw-scripts/unlock.sh

control + alt + t
    /usr/bin/kitty
